name: Execute Shell Script
on: push
jobs:
    first_job_from_execute_shell:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4 

            - name: List repo files
              run: | 
                    ls -lart
                    chmod +x ./shell_script.sh               

            - name: List and Read file
              run: ./shell_script.sh
    