name: My first workflow
on: push
jobs:
    first_job_from_first_example:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4 

            - name: List and Read file
              run: | 
                   echo " My first github action"
                   ls -lart
                   cat README.md



            # - name: list files
            #   run: ls
              
            # - name: read the file
            #   run: cat README.md

            
