name: WorkFloW_Dispath_Manually_trigger
on: workflow_dispatch
jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest,ubuntu-20.4,windows-latest]
        images: [nginx,alpine]
    runs-on: ${{matrix.os}}
    steps:
        - name: echo Docker details
          run: docker info

        - name: Run the image on matrix ${{matrix.os}}
          run: docker Run ${{matrix.images}}

    

 