name: WorkFloW_Dispath_Manually_trigger
on: workflow_dispatch
jobs:
  first_multi_job:
    runs-on: ubuntu-latest
    steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: List and Read file
          run: | 
                echo " My first github action" >> sample_text.txt
                ls -lart 
        - name: upload the file
          uses: actions/upload-artifact@v4
          with:
             name: my-artifact_file_from_previous_step
             path: sample_text.txt

  second_multi_job:
    needs: first_multi_job
    runs-on: ubuntu-latest
    steps:
     - name: download te file
       uses: actions/download-artifact@v4
       with:
         name: my-artifact_file_from_previous_step

     - name: validate shell script
       run: grep -i "first" sample_text.txt
  
  deploy_multi_job:
    needs: [first_multi_job,second_multi_job]
    runs-on: ubuntu-latest
    steps:
      - name: download the file
        uses: actions/download-artifact@v4
        with:
         name: my-artifact_file_from_previous_step

      - name: deploy the build
        run: cat sample_text.txt
